steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    # En önemli adım: GitHub Secrets'tan veriyi çekip cookies.txt dosyasını oluşturur
    - name: Cookie Dosyasını Oluştur
      run: |
        echo "${{ secrets.YT_COOKIES }}" > cookies.txt

    - name: Bağımlılıkları ve yt-dlp Kurulumunu Yap
      run: |
        sudo apt-get update
        sudo apt-get install -y python3
        sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Python Scriptini Çalıştır
      run: |
        python3 local_generator.py
